(cl:in-package tfg_real_env-msg)
(cl:export '(BALL_X-VAL
          BALL_X
          BALL_Y-VAL
          BALL_Y
          BALL_V_X-VAL
          BALL_V_X
          BALL_V_Y-VAL
          BALL_V_Y
          AGENT_X-VAL
          AGENT_X
          AGENT_Y-VAL
          AGENT_Y
          AGENT_THETA_X-VAL
          AGENT_THETA_X
          AGENT_THETA_Y-VAL
          AGENT_THETA_Y
          AGENT_V_X-VAL
          AGENT_V_X
          AGENT_V_Y-VAL
          AGENT_V_Y
          AGENT_V_THETA-VAL
          AGENT_V_THETA
          RIVAL_X-VAL
          RIVAL_X
          RIVAL_Y-VAL
          RIVAL_Y
          RIVAL_V_X-VAL
          RIVAL_V_X
          RIVAL_V_Y-VAL
          RIVAL_V_Y
          RIVAL_V_THETA-VAL
          RIVAL_V_THETA
))