# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tfg_real_env/obsmsg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class obsmsg(genpy.Message):
  _md5sum = "13d67f0b2acaa52762a3605ec7346fdb"
  _type = "tfg_real_env/obsmsg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 ball_x
float32 ball_y
float32 ball_v_x
float32 ball_v_y
float32 agent_x
float32 agent_y
float32 agent_theta_x
float32 agent_theta_y
float32 agent_v_x
float32 agent_v_y
float32 agent_v_theta
float32 rival_x
float32 rival_y
float32 rival_v_x
float32 rival_v_y
float32 rival_v_theta"""
  __slots__ = ['ball_x','ball_y','ball_v_x','ball_v_y','agent_x','agent_y','agent_theta_x','agent_theta_y','agent_v_x','agent_v_y','agent_v_theta','rival_x','rival_y','rival_v_x','rival_v_y','rival_v_theta']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ball_x,ball_y,ball_v_x,ball_v_y,agent_x,agent_y,agent_theta_x,agent_theta_y,agent_v_x,agent_v_y,agent_v_theta,rival_x,rival_y,rival_v_x,rival_v_y,rival_v_theta

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(obsmsg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.ball_x is None:
        self.ball_x = 0.
      if self.ball_y is None:
        self.ball_y = 0.
      if self.ball_v_x is None:
        self.ball_v_x = 0.
      if self.ball_v_y is None:
        self.ball_v_y = 0.
      if self.agent_x is None:
        self.agent_x = 0.
      if self.agent_y is None:
        self.agent_y = 0.
      if self.agent_theta_x is None:
        self.agent_theta_x = 0.
      if self.agent_theta_y is None:
        self.agent_theta_y = 0.
      if self.agent_v_x is None:
        self.agent_v_x = 0.
      if self.agent_v_y is None:
        self.agent_v_y = 0.
      if self.agent_v_theta is None:
        self.agent_v_theta = 0.
      if self.rival_x is None:
        self.rival_x = 0.
      if self.rival_y is None:
        self.rival_y = 0.
      if self.rival_v_x is None:
        self.rival_v_x = 0.
      if self.rival_v_y is None:
        self.rival_v_y = 0.
      if self.rival_v_theta is None:
        self.rival_v_theta = 0.
    else:
      self.ball_x = 0.
      self.ball_y = 0.
      self.ball_v_x = 0.
      self.ball_v_y = 0.
      self.agent_x = 0.
      self.agent_y = 0.
      self.agent_theta_x = 0.
      self.agent_theta_y = 0.
      self.agent_v_x = 0.
      self.agent_v_y = 0.
      self.agent_v_theta = 0.
      self.rival_x = 0.
      self.rival_y = 0.
      self.rival_v_x = 0.
      self.rival_v_y = 0.
      self.rival_v_theta = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_16f().pack(_x.ball_x, _x.ball_y, _x.ball_v_x, _x.ball_v_y, _x.agent_x, _x.agent_y, _x.agent_theta_x, _x.agent_theta_y, _x.agent_v_x, _x.agent_v_y, _x.agent_v_theta, _x.rival_x, _x.rival_y, _x.rival_v_x, _x.rival_v_y, _x.rival_v_theta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 64
      (_x.ball_x, _x.ball_y, _x.ball_v_x, _x.ball_v_y, _x.agent_x, _x.agent_y, _x.agent_theta_x, _x.agent_theta_y, _x.agent_v_x, _x.agent_v_y, _x.agent_v_theta, _x.rival_x, _x.rival_y, _x.rival_v_x, _x.rival_v_y, _x.rival_v_theta,) = _get_struct_16f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_16f().pack(_x.ball_x, _x.ball_y, _x.ball_v_x, _x.ball_v_y, _x.agent_x, _x.agent_y, _x.agent_theta_x, _x.agent_theta_y, _x.agent_v_x, _x.agent_v_y, _x.agent_v_theta, _x.rival_x, _x.rival_y, _x.rival_v_x, _x.rival_v_y, _x.rival_v_theta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 64
      (_x.ball_x, _x.ball_y, _x.ball_v_x, _x.ball_v_y, _x.agent_x, _x.agent_y, _x.agent_theta_x, _x.agent_theta_y, _x.agent_v_x, _x.agent_v_y, _x.agent_v_theta, _x.rival_x, _x.rival_y, _x.rival_v_x, _x.rival_v_y, _x.rival_v_theta,) = _get_struct_16f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_16f = None
def _get_struct_16f():
    global _struct_16f
    if _struct_16f is None:
        _struct_16f = struct.Struct("<16f")
    return _struct_16f
